export interface BaseAnalyticsFilter {}
export interface TransactionVolumeFilter {}
export interface TransactionsByTypeFilter {}
export interface RevenueTrendsFilter {}
export interface PaymentVolumeFilter {}
export interface PaymentsByCategoryFilter {}
export interface BillPaymentsFilter {}
export interface FlightBookingsFilter {}
export interface TransactionSummaryFilter {}
export interface ComprehensiveAnalyticsFilter {}
export interface AnalyticsData {}
